After first deploy

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -2,4 +2,12 @@
 
 bindir=`dirname $0`
 
+if [[ ! -x `which gpg-agent` ]]; then
+  echo "Can't find gpg-agent"
+  exit 1
+fi
+
+eval $(gpg-agent --daemon)
+gpg --quiet --batch --decrypt ~/.lein/credentials.clj.gpg
 $bindir/lein deploy clojars
+pkill gpg-agent
